#!/bin/bash	
# Pobiera z gihtuba najnowszą werjse dofilesów i instaluje je na lokalnym komputerze.
cd ~ && git clone git://github.com/sbogutyn/dotfiles.git && cd ~/dotfiles && chmod +x install.sh && ./install.sh